### ISSUE TITLE
todo-modern: Can't add two todos with the same text

### ISSUE THREAD

**Issue by taion** [relayjs/relay-examples#30]
I believe the issue is that `AddTodoMutation` is using just `text` as its input, and is not using a `clientMutationId`.

Is the idea with Relay Modern that mutations that require client mutation IDs must generate one in user code?

**Comment by wincent** [comment]
Good catch!

> Is the idea with Relay Modern that mutations that require client mutation IDs must generate one in user code?

That is what we've been doing internally, because we didn't want to bake into the runtime the assumption that mutations must have a client ID (even though [the spec](http://facebook.github.io/relay/graphql/mutations.htm) calls for it, a number of questions have come up asking whether it is strictly necessary; we mostly concluded that they were in there for historical reasons and they could arguably be useful on some client implementations, but Relay itself doesn't *need* them).

**Comment by taion** [comment]
I ended up doing https://github.com/taion/relay-todomvc/blob/98f473abb07fcd1c4340ebcd9b48d350b7c0c818/src/mutations/AddTodoMutation.js#L36-L45, and it worked.

**Comment by alangenfeld** [comment]
thanks!

**Comment by sibelius** [comment]
fixed here https://github.com/facebook/relay/commit/c988815ff9b1b4dd236c83413c55b352bbae0266
