### ISSUE TITLE
Add example with authentication

### ISSUE THREAD

**Issue by singingwolfboy** [relayjs/relay-examples#51]
The [documentation for environments](https://facebook.github.io/relay/docs/relay-environment.html) mentions creating a new environment instance whenever the user logs in or out in order to prevent data for different users being cached together. This seems like a very common usage pattern, but the documentation doesn't show any examples of how to do it. The `todo` example in this repository doesn't handle logging in and logging out, so it doesn't show how to do it, either.

[There is a StackOverflow question that discusses how to do this](https://stackoverflow.com/questions/44659157/handling-authentication-in-relay-modern), but it's light on details. It also refers to storing the environment in component state, which is not shown in the `todo` example in this repository.

Could you add an example to this repository that shows how to create a fresh environment instance when a user logs in?

**Comment by singingwolfboy** [comment]
The documentation also discusses `handlerProvider`, but doesn't explain what the benefit is of using it. Based on the code sample in the documentation, it seems like the `ViewerHandler` might be useful for handling authentication, but there's no documentation for what this `ViewerHandler` object is or what it actually does. This also seems like it merits an example.

**Comment by yuzhi** [comment]
Specific authentication implementation is outside the scope of Relay, which is a GraphQL client to handle GraphQL data. It's recommended to make a completely new environment when users log in and/or out like specified in Stackoverflow in order to start fresh without potential privacy issues. It's pretty error prone if you try to share partial data between users. When the new environment is created is dependent on your authentication logic. `handleProvider` is used for custom logic when storing graphql data in Relay, but is not relevant for authentication.

**Comment by singingwolfboy** [comment]
> Specific authentication implementation is outside the scope of Relay, which is a GraphQL client to handle GraphQL data.

I understand that there are many different ways to implement authentication, and server-side authentication handling is outside the scope of Relay. However, client-side authentication handling is _definitely_ within the scope of Relay, since Relay needs to be able to make authenticated requests to the GraphQL endpoint. The whole point of a `relay-examples` repository is to show examples of how to use Relay correctly, and authentication is a complicated topic that deserves an example.

> It's recommended to make a completely new environment when users log in and/or out like specified in Stackoverflow in order to start fresh without potential privacy issues. It's pretty error prone if you try to share partial data between users.

The fact that there is a recommendation like this, clearly illustrates that Relay needs to handle authentication somehow.

> When the new environment is created is dependent on your authentication logic.

Of course. I'm asking for a simple example that shows one possible way of creating a new environment.

> `handleProvider` is used for custom logic when storing graphql data in Relay, but is not relevant for authentication.

This is useful information: thank you! The documentation wasn't clear on this, which is why I thought that `handleProvider` might be relevant to authentication. An example of handling authentication with a Relay-enabled app would make it even clearer.

There is already a [User model for the `todo` example](https://github.com/relayjs/relay-examples/blob/master/todo/data/database.js#L14). I would recommend making the following changes, in order to make an example that illustrates how to handle authentication with Relay:

* Extend the User model by adding three fields: `username`, `password`, and `apiToken`.
* Create `login` mutation, that takes `username` and `password` as input. If the `username` and `password` match a user in the database, return that user's `apiToken`.
* After the client executes the `login` mutation, create a new environment (this is what I'm most interested in seeing!) and save the `apiToken` to [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) or [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).
* Every time Relay makes a query, check sessionStorage or localStorage for an `apiToken`. If one exists, add an [`Authorization` request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) with that token.

**Comment by yuzhi** [comment]
>  However, client-side authentication handling is definitely within the scope of Relay, since Relay needs to be able to make authenticated requests to the GraphQL endpoint. 

Github listed three potential ways to authenticate here: https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb. We recommend doing authentication through a different endpoint and make sure your custom network layer has the relevant info to send authenticated request to the GraphQL endpoint. I would like to echo that post and also say that the third option is something that I've not seen done in production and thus not sure it a pattern we want to encourage. Doing a simple mutation won't resetting existing data in the cache, so you would still have to Create a new environment (to clear out data from potential previous users) and make sure your network layer can use the token for requests.
Info about that here:
https://facebook.github.io/relay/docs/relay-environment.html#a-simple-example https://facebook.github.io/relay/docs/network-layer.html

> Extend the User model by adding three fields: username, password, and apiToken.

I think it will be a terrible idea to add `password` to any Model. The server should not send that down for authentication. Please please don't do this.

>  Create login mutation, that takes username and password as input. If the username and password match a user in the database, return that user's apiToken.

You can get the apiToken in graphql, but you can do that with any endpoint. Relay is agnostic to that. As mentioned above, I have not seen this pattern in production. You still have to create a new environment to avoid cross user data sharing. It's not very interesting to commit the mutation in the Relay store because we should theoretically be making a new store/environment anyways.

**Comment by singingwolfboy** [comment]
Thank you for providing this information, as well. The docs are sorely lacking on this, and I wasn't aware of [that blog post about authentication](https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb). However, this _still_ doesn't resolve my issue.

You say that I have to create a new environment when a user logs in. That's fine, that's what I was expecting from the start of filing this issue. What I need is some example code that does that. I don't know _how_ to create a new environment.

Could you (or someone else who works on Relay) show me _how_ to create a new environment? That's really what I'm looking for in an authentication example.

**Comment by mike-marcacci** [comment]
Hi @singingwolfboy,

Just stumbled on your issue while looking for something else, but I can help. Here's my environment config file. You can see that I fetch my session ID on each request (which is just stored in the browser's `localStorage`) and adds it the the HTTP `Authorization` header (which is what my API checks).

```es6
import {
	Environment,
	Network,
	RecordSource,
	Store,
} from 'relay-runtime';

import * as session from './session';

const source = new RecordSource();
const store = new Store(source);
const network = Network.create(async (
	operation,
	variables,
	cacheConfig,
	uploadables,
) => {
	const headers = {
		'Content-Type': 'application/json',
	};

	// get our session identifier
	const sessionId = session.get();
	if (sessionId) {
		headers['Authorization'] = `Bearer ${sessionId}`;
	}

	// make the HTTP request
	const response = await fetch('/graphql', {
		method: 'POST',
		headers: headers,
		body: JSON.stringify({
			query: operation.text,
			variables: variables,
		}),
	});

	// we are using an invalid session, get rid of it
	if (response.status === 401) {
		session.clear();
	}

	// there was an error communicating with the API
	if (!response.ok) {
		console.error(`API ERROR: ${await response.text()}`);
		throw new Error(response.statusText);
	}

	// parse the JSON response
	return response.json();
});

const environment = new Environment({
	handlerProvider: null,
	network,
	store,
});

export default environment;
```


Elsewhere in the app, I use a Relay mutation to authenticate (using my API's `authenticate` mutation). I use `authority` and `proof` here, which is abstract over a bunch of different authentication strategies (ID/Email + Password, ID + Password Reset Token, Google, Facebook, etc) but you can just replace these with whatever you want to use, like `username` and `password`. The mutation, if successful, returns a new `Session`, so we'll make sure to grab it's ID. We then stuff that ID in `localStorage` so that the next time we make a GraphQL query, we're authenticated!

```es6
const mutation = graphql`
	mutation AuthenticateFormMutation($authority: Authority!, $proof: String!) {
		authenticate(authority: $authority, proof: $proof) {
			message
			session {
				id
			}
		}
	}
`;
```

Of course, with this strategy you can't put the *entirety* of your API behind authentication, since at least the `authenticate` mutation needs to be accessible without a session.


---


Perhaps a simpler strategy would be to simply send a username/password pair with each request, using something like http `Basic` in the `Authorization` header. This certainly has its security and visibility downsides, but might be an easier way to get a working prototype.

Hope that helps.

**Comment by steida** [comment]
I have an example in https://github.com/este/este
